input {
  file {
    path => "/var/log/apache2/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if "OR" in [message] {
    mutate {
      add_tag => ["SQLi_Attack"]
    }
  }
}

output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cyber-logs"
  }

  if "SQLi_Attack" in [tags] {
    http {
      url => "http://response-engine:5000/block_ip"
      http_method => "post"
      format => "json"
      mapping => {
        "ip" => "%{host}"
      }
    }
  }
}
